include <util.scad>
include <params.scad>

STABILIZER_OUTER_WIDTH = 29;
STABILIZER_INNER_WIDTH = 24;
STABILIZER_VERTICAL_INSET = 2.5;

module Stabilizer()
{
	LARGE = 100;
	difference() {
		Rect(STABILIZER_OUTER_WIDTH, STABILIZER_HEIGHT, ANCHOR_TC);
		Rect(STABILIZER_INNER_WIDTH, STABILIZER_VERTICAL_INSET, ANCHOR_TC);
	}
}

Stabilizer();
