include <util.scad>
include <params.scad>

STABILIZER_OUTER_HALF_WIDTH = 14.5;
STABILIZER_INNER_HALF_WIDTH = 12;
STABILIZER_VERTICAL_INSET = 2.5;

module Stabilizer()
{
	LARGE = 100;
	difference()
	{
		Rect(STABILIZER_OUTER_HALF_WIDTH*2, STABILIZER_HEIGHT, ANCHOR_TC);
		Rect(STABILIZER_INNER_HALF_WIDTH*2, STABILIZER_VERTICAL_INSET, ANCHOR_TC);
	}
}

Stabilizer();
